fix error on no ability
cannedyeti/ultimate-bravery-v3 pull request #20
Opened 2024-05-23 17:34 UTC by brycerobinsn

![image](https://github.com/cannedyeti/ultimate-bravery-v3/assets/80009651/d50af17a-b04f-49bc-be30-2a4ea342ed3f)

I think my last PR didn't have your fix for the no ability crash :)

2024-05-23 22:47 UTC, cannedyeti requested changes

2024-05-23 22:47 UTC, cannedyeti commented on src/features/bravery/components/RandomItems.jsx
> +        <Tooltip label={abilityTooltipLabel} >
```suggestion
        <Tooltip label={<TooltipCard header={ability?.name} body={ability.description} /> || ABILITY_ARRAY[state.selectedRandomAbilityIndex]}} >
```

can just do this xd

2024-05-23 22:47 UTC, cannedyeti commented on src/features/bravery/components/RandomItems.jsx
> +            src={abilityAvatarSrc}
```suggestion
            src={ability?.name ? `${SPELL_IMAGE_BASE_URL}${ability?.image?.full}` : <WarningTwoIcon />}
```

Rather just do ternary here. Cleaner than random ifs

2024-05-23 22:47 UTC, cannedyeti commented on src/features/bravery/components/RandomItems.jsx
> +  let abilityAvatarSrc = <WarningTwoIcon />;
good to use `const` over `let` if you're never altering the variable. But I don't think we need these after changes are made anyway

2024-05-23 23:00 UTC, brycerobinsn commented on src/features/bravery/components/RandomItems.jsx
> +        <Tooltip label={abilityTooltipLabel} >
this was still popping an error. Switched to ternary

2024-05-25 03:33 UTC, cannedyeti approved these changes

2024-05-25 03:34 UTC, merged